import { NextResponse } from 'next/server';
import axios from 'axios';
import { config } from 'dotenv';
import admin from 'firebase-admin';

config(); // Load environment variables

//Firebase Admin SDK initialization
if (!admin.apps.length) {
  const projectId = process.env.FIREBASE_PROJECT_ID;
  const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;
  const privateKey = process.env.FIREBASE_PRIVATE_KEY;

  if (!projectId || !clientEmail || !privateKey) {
    throw new Error("Missing Firebase Admin credentials in environment variables.");
  }

  admin.initializeApp({
    credential: admin.credential.cert({
      projectId,
      clientEmail,
      privateKey: privateKey.replace(/\\n/g, '\n'),
    }),
  });
}

const db = admin.firestore();

export async function POST(request) {
  try {
    const authHeader = request.headers.get('Authorization');

    const idToken = authHeader.split('Bearer ')[1];
    const decodedToken = await admin.auth().verifyIdToken(idToken);
    const userId = decodedToken.uid;

    // Extract pantry items
    const { pantryItems } = await request.json();
    if (!pantryItems || pantryItems.length === 0) {
      return NextResponse.json({ error: "No pantry items provided" }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: "GEMINI_API_KEY is not set" }, { status: 500 });
    }

    // Fetch existing recipe titles
    const recipesRef = db.collection('users').doc(userId).collection('recipes');
    const snapshot = await recipesRef.get();
    const existingTitles = snapshot.docs.map(doc => doc.data().title?.toLowerCase?.() ?? '');

    // Prompt Creation
    const prompt = `
      Create a unique recipe using only the following ingredients: ${pantryItems.join(", ")}, plus basic staples like salt, pepper, oil, and water.

      Format like:
      **Title:** <Short recipe name (max 20 characters)>
      **Ingredients:**
      * item1
      * item2
      **Instructions:**
      1. Step one
      2. Step two

      Ensure:
      - The title is no more than 20 characters.
      - The title and cuisine differ from these existing ones: ${existingTitles.join(", ") || 'none'}.
      - The cuisine should be unique (e.g., Italian, Indian, Japanese, etc.).
      `;

    const response = await axios.post(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent",
      { contents: [{ parts: [{ text: prompt }] }] },
      {
        headers: {
          "Content-Type": "application/json",
          "X-goog-api-key": apiKey,
        },
      }
    );

    const rawRecipe = response.data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!rawRecipe) {
      return NextResponse.json({ error: "No recipe generated by Gemini" }, { status: 500 });
    }

    // Parse the recipe
    const formattedRecipe = { title: '', ingredients: [], instructions: [] };
    const lines = rawRecipe.split('\n').map(line => line.trim()).filter(Boolean);
    let currentSection = null;

    for (const line of lines) {
      //Parse API response 
      if (!formattedRecipe.title && /title:/i.test(line)) {
        formattedRecipe.title = line.split(/title:/i)[1]?.trim() || 'Untitled Recipe';
      } else if (/ingredients:/i.test(line)) {
        currentSection = 'ingredients';
      } else if (/instructions:/i.test(line)) {
        currentSection = 'instructions';
      } else if (currentSection === 'ingredients' && /^\*\s+/.test(line)) {
        formattedRecipe.ingredients.push(line.replace(/^\*\s+/, '').trim());
      } else if (currentSection === 'instructions' && /^\d+\.\s+/.test(line)) {
        formattedRecipe.instructions.push(line.replace(/^\d+\.\s+/, '').trim());
      }
    }

    // Fallbacks
    if (!formattedRecipe.title) formattedRecipe.title = 'Generated Recipe';
    if (formattedRecipe.ingredients.length === 0) formattedRecipe.ingredients.push('No ingredients listed');
    if (formattedRecipe.instructions.length === 0) formattedRecipe.instructions.push('No instructions available');

    return NextResponse.json({ recipe: formattedRecipe });

  } catch (error) {
    console.error("Error in /api/recipes:", error);
    return NextResponse.json({ error: `Failed to generate recipe: ${error.message}` }, { status: 500 });
  }
}
