'use client';

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import LoadingScreen from "./components/loadingScreen";
import { LoadingProvider } from "./context/LoadingContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);

    const timer = setTimeout(() => {
      setLoading(false);
    }, 400); // You can increase this if your content takes longer to load

    return () => clearTimeout(timer);
  }, [pathname]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <LoadingProvider>
            {loading ? <LoadingScreen /> : children}
          </LoadingProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
